### ISSUE TITLE
Height and Weight data beyond

### ISSUE THREAD

**Issue by hathawayj** [growthcharts/brokenstick#5]
Stef,

   I am looking for some additional child height and weight data for other countries that I could use in an introductory data science class.  Do you happen to have any leads to additional public data?

Here is the one you describe in the package.

Longitudinal height and weight measurements during ages 0-2 years for a representative sample of 1933 Dutch children born in 1988-1989. The dataset smocc_hgtwgt is a subset of the full data covering the first 206 children.

Thanks,

J.

**Comment by stefvanbuuren** [comment]
I often use `mice::boys` or `AGD::boys7482` for teaching. Stef.

**Comment by hathawayj** [comment]
thanks
