### ISSUE TITLE
plotting imputed trajectories

### ISSUE THREAD

**Issue by ghost** [growthcharts/brokenstick#8]
Dear Stef,
I have an issue with trying to plot multiply imputed trajectories based on the brokenstick model. I get the following error message
`Error in FUN(X[[i]], ...) : object 'hgt_z' not found`
which I think is related to this code chunk from `plot_trajectory()` where you refer to "hgt_z" which is named differently in my analysis.
`k <- data$.source == "imputed"
    if (any(k)) {
        g <- g + ggplot2::geom_line(ggplot2::aes_string(group = ".imp"), 
            data = data[k, ], color = color_imp[2L]) + ggplot2::geom_point(ggplot2::aes_string(y = "**hgt_z**"), 
            data = data[k, ], color = color_imp[1L], size = size_imp)
    }`
If I rename my outcome variable to `hgt_z` everything works fine.
Kind regards
Ben

**Comment by stefvanbuuren** [comment]
Thanks for noting. This commit fixes the problem.
