### ISSUE TITLE
more than two predictors

### ISSUE THREAD

**Issue by ndsubison2178** [growthcharts/brokenstick#9]
How do I add more than two predictors : 1) Age 2) BMI in the **brokenstick** model and how do I ensure that the knots function is only for Age variable and not BMI ? Thanks.

**Comment by stefvanbuuren** [comment]
The `brokenstick` package is designed to handle only one predictor. 

My suggestion is to split your analysis into two steps: First fit the brokenstick model on age, then model BMI on the brokenstick estimates. In that way, BMI does not influence the brokenstick transformation.

**Comment by ndsubison2178** [comment]
Okay thank you very much.
